apiVersion: v1
kind: Pod
metadata:
 name: pod-nginx
 labels:
   app: nginx
   service: web
spec: # required
 containers:
   - image: nginx:latest
     name: contenedor-nginx
     imagePullPolicy: Always
